// Code generated by "stringer -type=txnState"; DO NOT EDIT.

package funclown

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[txnBefore-0]
	_ = x[txnTerm-1]
	_ = x[txnAfter-2]
}

const _txnState_name = "txnBeforetxnTermtxnAfter"

var _txnState_index = [...]uint8{0, 9, 16, 24}

func (i txnState) String() string {
	if i < 0 || i >= txnState(len(_txnState_index)-1) {
		return "txnState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _txnState_name[_txnState_index[i]:_txnState_index[i+1]]
}
